@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjcxMzMzOTgsInVzZXJpZCI6MX0.zlldgx2pYdrC95o3b3y74WIjVPREeyAb4tpXUby-I1M
@number = 4
### appVersion

GET  http://localhost:8080/

### create user

POST http://localhost:8080/users
# Authorization: Bearer {{token}}
Content-Type: application/json

{
    "firstName":"test{{number}}",
    "lastName":"test{{number}}",
    "email":"test{{number}}"
}